[	NAME			SET_PATH_METHOD		CLOSE_METHOD	LINK_POPUP						PATH_FIELD_CONTROL_ID]

	; OneNote			POPUP_FIELD			ENTER			Link ahk_class NUIDialog		RICHEDIT60W2
	OneNote			CLIPBOARD
	Outlook			POPUP_FIELD			ENTER			ahk_class bosa_sdm_Mso96		RichEdit20W6
	PowerPoint		POPUP_FIELD			ENTER			ahk_class bosa_sdm_Mso96		RichEdit20W6
	Word			POPUP_FIELD			ENTER			ahk_class bosa_sdm_msword		RichEdit20W6

	EMC2			WEB_FIELD			ALT_A
	EMC2 Popup		WEB_FIELD			ALT_A
	Teams			WEB_FIELD			ENTER
