(	NAME					ABBREV			PATH																														MACHINE

	# General
	Downloads			dl|downloads	<USERROOT>\Downloads\
	Shortcuts			sc					<USERROOT>\Shortcuts\																								EPIC_LAPTOP
	Music					mu					<USERROOT>\Music\																										HOME_DESKTOP|HOME_ASUS
	Music					mu					<USERROOT>\Music\																										EPIC_LAPTOP
	Public				pub				F:\Personal\gborg\Public\																							EPIC_LAPTOP
	
	# System
	Startup				start				<USERROOT>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\
	Pinned Shortcuts	ps					<USERROOT>\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\
	EpicStudio Config	esc				<USERROOT>\AppData\Local\Epic Systems Corporation\EpicStudio											EPIC_LAPTOP
	
	; # Development
	Item Approval		ia					\\epic.com\files\docs\Hospital Billing\Designs\Items Approval											EPIC_LAPTOP
	
	# Setup
	VM Templates		vt					\\epic.com\files\apps\vmware\SU Development																	EPIC_LAPTOP
	
	# For Hotkeys
	AHK Root				ar|ahkRoot		<AHKROOT>\
	AHK Config			ac|ahkConfig	<AHKROOT>\config\

	# Reason Not Collecting
	Screenshots			rnc				F:\personal\gborg\Screenshots\Reason Not Collecting														EPIC_LAPTOP
