=Choose a unit test to run or generate:

(	NAME						ABBREV		AREA				INPUT							OUTPUT								SOURCE							SUBAREA

	TableList				tl				TableList		tableList.ini				tableListOutput.txt
	TableList Settings	tls			TableList		tableListSettings.ini	tableListSettingsOutput.txt	\x									SETTINGS
	Selector 1				sel1			Selector			selectorMain.ini			selectorMainOutput.txt			selectorMainSource.ini		
	Selector 2				sel2			Selector			selectorData.ini			selectorDataOutput.txt			selectorDataSource.ini		DATA
