=Choose a unit test to run or generate:

(	NAME						ABBREV		AREA				INPUT							OUTPUT								SOURCE							SUBAREA

	TableList				tl				TableList		tableList.tl				tableListOutput.txt
	TableList Settings	tls			TableList		tableListSettings.tl		tableListSettingsOutput.txt	\x									SETTINGS
	Selector 1				sel1			Selector			selectorMain.tl			selectorMainOutput.txt			selectorMainSource.tl		
	Selector 2				sel2			Selector			selectorData.tl			selectorDataOutput.txt			selectorDataSource.tl		DATA
