@PlaceholderChar=-

=Select Machine to set up:
+ShowArbitraryInputs=1
+MinColumnWidth=1000

(	NAME					ABBREV		WHICH_MACHINE		VIM_CLOSE_KEY	MENU_KEY_ACTION	EDGE_OFFSET		MAX_EXTRA_EDGE_OFFSET
)	0						0				0						1					2						3					4

	Home Desktop		desk			HOME_DESKTOP		F8|F9				-						7					1                      
	Home Laptop			laptop		HOME_LAPTOP			F8|F9|F10		WINDOWS_KEY			7					1
	Epic Desktop		epic			EPIC_DESKTOP		F6					WINDOWS_KEY